apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.model | dump}}
  annotations:
    backstage.io/source-location: url:https://${{values.host}}/${{values.destination}}
    backstage.io/techdocs-ref: url:https://${{values.host}}/${{values.destination}}
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces-${{values.cluster}}/#https://${{values.host}}/${{values.destination}}
      title: OpenShift Dev Spaces (VS Code)
      icon: web
